### ISSUE TITLE
Event when reCaptcha modal was closed

### ISSUE THREAD

**Issue by karolgorecki** [szchenghuang/react-google-invisible-recaptcha#12]
Is there a event, callback when the user cancel/closes the reCaptcha modal?
I would like to create loading state when the reCaptcha is resolving
and reset the loading state when the captcha was resolved / canceled.

**Comment by szchenghuang** [comment]
I see how it improves users' experience, but I am not aware of one provided by the core service. If you really need it, one hack is to perform an analysis based on its HTML structure.

Since there is no consensus on the structure, that hack will break once it is changed.
