### ISSUE TITLE
Error: reCAPTCHA has already been rendered in this element when unmounting and mounting again

### ISSUE THREAD

**Issue by aalises** [szchenghuang/react-google-invisible-recaptcha#17]
Hello @szchenghuang , I found out another issue which may be related to this PR #16 . When I unmount the component and mount it again, this happens:
![screenshoterror](https://user-images.githubusercontent.com/11021461/41219891-0388b8fe-6d60-11e8-83f6-55338a04131b.png)

Somehow the references to the container and the elements are not deleted correctly on ComponentWillUnmount. calling grecaptcha.reset() on component unmount does not seem to fix it either. However, when reloading the page the reCaptcha works as expected, any idea?

Edit: The exact same problem happened [Here](https://github.com/dozoisch/react-google-recaptcha/issues/55), and was fixed by [removing the rendered DOM on unmounting](https://github.com/dozoisch/react-google-recaptcha/pull/73/commits/e8819437887facec1bf9d3f884cb329adc39f62a)

**Comment by szchenghuang** [comment]
Cool! It does seem related to #16 and similar issues. Your PR #18 will be merged. I am wishing that it will fix them all together.

Thanks for your feedback and PR!

**Comment by aalises** [comment]
Hello!
Thank you @szchenghuang !!  :tada: I have been running a local copy with the changes in a project for some days now, and so far have not run into any more errors :+1:

**Comment by szchenghuang** [comment]
My pleasure. A patch will be released soon.
