### ISSUE TITLE
How can I use it in a functional component without ref and can I load the execute() from componentWillMount rather than a click event

### ISSUE THREAD

**Issue by sschenk** [szchenghuang/react-google-invisible-recaptcha#2]
First of all I'm trying to use it in a stateless function like so:
```

const Form = (props) => (
  <form>
       <Recaptcha
         ref='' //Without a ref field resolve is never called
         sitekey='someKey'
         onResolved={props.onResolved} />
  </form>
) 
```

But without a ref field resolved is never called. How do I solve this?

Second question:

I have another use case where I would like to call the recaptche on componentWillMount or similar and not when a user submits a form I've tried simply putting this.recaptcha.execute() in the life cycle method, but resolve never gets called and I'm actually not sure if a request to google is even made. Is what I'm trying to achieve possible?

**Comment by szchenghuang** [comment]
In your Form component the callback onResolve did not get called since it makes no request to invoke a recaptcha check. Prop ref is meant to be accessed so that a check can be invoked.

Trying to run recaptcha in componentWillMount is not supported. We need to wait on DOM rendering and then access DOM via ref to run recaptcha.

**Comment by sschenk** [comment]
I'm sorry for not being more clear. I understand the ref invokes the check, my question was how can I use it with a stateless function which doesn’t have a backing instance so it can't use ref?

**Comment by szchenghuang** [comment]
Sorry for getting back late. The procedure of reCAPTCHA is more a stateful behavior than a presentational component. It is not supposed to be used without access to the ref.
