### ISSUE TITLE
Safari bug, The source list for Content Security Policy directive 'script-src' contains an invalid source: ''strict-dynamic''. It will be ignored. 4

### ISSUE THREAD

**Issue by arelaxend** [szchenghuang/react-google-invisible-recaptcha#23]
Dear contributors,

`The source list for Content Security Policy directive 'script-src' contains an invalid source: ''strict-dynamic''. It will be ignored.`

The bug appears in the "demo" link of the page.

On Safari Version 12.0 (13606.2.11)

A.

Edit: reference here https://github.com/google/google-api-javascript-client/issues/397

**Comment by arelaxend** [comment]
Here, they specify to use none https://developers.google.com/recaptcha/docs/faq#im-using-content-security-policy-csp-on-my-website-how-can-i-configure-it-to-work-with-recaptcha

I put the following as a try in my index.html
```
  <meta http-equiv="Content-Security-Policy" content="
    script-src 'self' 'nonce-ch4hvvbHDpv7xCSvXCs3BrNggHdTzxUA';
    frame-src 'self' 'nonce-ch4hvvbHDpv7xCSvXCs3BrNggHdTzxUA' ;
    style-src 'self' 'unsafe-inline';
    object-src 'self';
  ">
```

And, I add:
```
  var script = document.createElement('script');
  ...
  script.nonce = 'ch4hvvbHDpv7xCSvXCs3BrNggHdTzxUA';
```

And now, I am still getting the following error... unbelievable

`Refused to load https://www.google.com/recaptcha/api2/anchor?ar=1&k=***=fr&v=v1536705955372&size=invisible&badge=inline&cb=*** because it does not appear in the frame-src directive of the Content Security Policy.`

**Comment by arelaxend** [comment]
Ok, I found that is might or might not be relevant.
In their demo, https://www.google.com/recaptcha/api2/demo?invisible=true
They put a nonce for the script, but no meta. And it works, I did the test with the package.

**Comment by youriv2019** [comment]
this bug caused my website to stop working. I have taken recaptcha away now.
