### ISSUE TITLE
TypeError: this.reset is not a function

### ISSUE THREAD

**Issue by sandy0201** [szchenghuang/react-google-invisible-recaptcha#26]
Hi @szchenghuang ,

Recently I got this error as in the title of this issue, not sure where it could be going wrong.

Here's a screenshot of the error on the page and console errors logged:
![image](https://user-images.githubusercontent.com/2969051/46523534-47c3fe80-c886-11e8-98e4-5a60e49c0b3a.png)

It would be great to know what could be causing this error.

Thank you.
Kind regards.

**Comment by szchenghuang** [comment]
@sandy0201 Just merged #27 which solves this issue. If you update to the latest release, this will be included. Thanks.

**Comment by sandy0201** [comment]
Thanks @szchenghuang for the update.
