### ISSUE TITLE
React upgrade halted due to dependency

### ISSUE THREAD

**Issue by isaacrowntree** [szchenghuang/react-google-invisible-recaptcha#3]
npm install -D react@16
frontend@1.0.0 ../
├── node-pre-gyp@0.6.36
├── UNMET PEER DEPENDENCY react@16.0.0
└─┬ react-google-invisible-recaptcha@0.1.1
  └── react@15.6.2

Can you please provide a new version pushing to the new React?

**Comment by szchenghuang** [comment]
I just upgrade dependencies and release a new version 0.2.0. I will close this ticket now. Please reopen if  any error is triggered with such upgrade. Thanks for poking.
