### ISSUE TITLE
Cannot contact reCAPTCHA. Check your connection and try again 

### ISSUE THREAD

**Issue by siddushar** [szchenghuang/react-google-invisible-recaptcha#5]
I am trying to use invisible reCAPTCHA, when i load page it shows alert like "Cannot contact reCAPTCHA. Check your connection and try again". i am following documentation to use this. can any one help?

**Comment by szchenghuang** [comment]
I just visited the demo page. Since it is still functioning, I would suggest trying another browser, checking if cookies are allowed, or making sure your firewall is not blocking the connection. Sometimes it occurs when CPU is overloaded.

**Comment by stasov** [comment]
@siddushar Have you updated the "sitekey" value with a valid key that you've received when registering for the ReCaptcha service?

**Comment by siddushar** [comment]
Thanks @szchenghuang it was cookie problem. it is working for me.

**Comment by matviishyn** [comment]
Remove current REcaptcha key, then register new key and set your **key settings** with domains:
```
127.0.0.1
localhost
```

**Comment by ashashingadia** [comment]
@siddushar How you solved cookie problem??can you please explain

**Comment by adimittal** [comment]
My issue was I had changed the domain name in my virtual host.  Adding the domain name to the recaptcha domains list fixed it.

**Comment by DFOXpro** [comment]
Also note you can't use recaptcha v2 keys (it use a different contract) so you need to create a new key with the invisible type (not the v2)

**Comment by siddushar** [comment]
Create  reCAPTCHA and add valid URL. it will work without any issue.

**Comment by m07amad** [comment]
if you use chrome go to sittings>Privacy and security>Protect you and your device from dangerous sites disable it

**Comment by sjsnider** [comment]
have been getting reports of this happening to users but I can't ever recreate, is there a callback or something to catch when this happens for better error handling?

**Comment by saravanasksk** [comment]
Just disabled the extension (in my side it's urban vpn) and it resolved the issue
