### ISSUE TITLE
Ability to remove `display:none`

### ISSUE THREAD

**Issue by willfarrell** [szchenghuang/react-google-invisible-recaptcha#6]
As per [Google Terms of Service](https://www.google.com/intl/en/policies/terms/) `Don’t remove, obscure, or alter any legal notices displayed in or along with our Services.` Sooo, hiding it can get you kicked from the service.

Because hiding it can be very useful, my suggestion would be to add a prop like `display` that can toggle the visibility.

**Comment by szchenghuang** [comment]
Suggestion taken. Thanks for the caution.

I will probably replace the new `display` prop with a `style` prop sooner or later.

**Comment by willfarrell** [comment]
Sounds good, looking forward to seeing the update.
